import Head from 'next/head'
import Intro from '../components/Intro'
import Services from '../components/Services'
import Testimonials from '../components/Testimonials';
import { data } from "../data";
//import styles from '../styles/Home.module.css'

export default function Home({ services }) {
  
  return (
    <div>
      <Head>
        <title>Agency App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      
      <Intro />
      <Services services={ services }/>
      <Testimonials />
     
    </div>
  )
}

export const getStaticProps = () => { // Este método nos permite buscar cualquier dato antes de renderizar los componentes
  const services = data;              // o páginas
  return {
    props: { services },
  };
};
